### ISSUE TITLE
add ol3editor application to wordpress

### ISSUE THREAD

**Issue by Redagou** [programmerg/ol3editor#3]
I am using wordpress to creat a website contain a GIS application. So i did upload the project (files) from Github and I did done some changes to adapte this project to my needs but I found some problems to display this application in wordpress and add some type of files(Github) to my wordpress repertoire like : file.md , file.bat, file.gitignore. 

I tried some solutions like iframe but i connect connect to the database so i am searching for other options. Thank you

**Comment by programmerg** [comment]
To kick start OL3Editor you will need [ol.editor.css](https://github.com/programmerg/ol3editor/tree/master/dist/ol.editor.css) and [ol.editor.js](https://github.com/programmerg/ol3editor/tree/master/dist/ol.editor.js) files from the [dist](https://github.com/programmerg/ol3editor/tree/master/dist) folder, and the thrid-party [ol.css](http://openlayers.org/en/master/css/ol.css) and [ol.js](http://openlayers.org/en/master/build/ol.js) files. Make sure, your upload folder and this files in it are accessible from the browser. After than follow my [getting started](https://github.com/programmerg/ol3editor#getting-started) guide (or the full-featured [index.html](https://github.com/programmerg/ol3editor/tree/master/index.html)), how to include this files in your WP theme / plugin. If you get stuck, press `Ctrl+Shift+i` in Chrome and check the messages in console tab.

**Comment by Redagou** [comment]
it's work very well.... Thank you
